### ISSUE TITLE
선생님은 대시보드에 로그인할 수 있다.

### ISSUE THREAD

**Issue by chayeoi** [chayeoi/learning-manager#1]
## Tasks

- [x] 인증되지 않은 사용자가 대시보드에 접근 시 로그인 화면으로 리다이렉트되어야 한다.
- [x] 인증된 사용자가 로그인 화면에 접근하면 대시보드로 리다이렉트되어야 한다.
- [x] 사용자는 구글 계정을 통해 소셜 로그인할 수 있어야 한다.
- [x] 화면 새로고침 시 로그인 상태가 유지되어야 한다.
