### ISSUE TITLE
선생님은 문제지를 삭제할 수 있다.

### ISSUE THREAD

**Issue by chayeoi** [chayeoi/learning-manager#12]
## Tasks

- [ ] 문제지 목록에서 개별 문제지를 선택하여 삭제(숨김 처리)
- [ ] 문제지 상세 화면에서 개별 문제지 삭제
- [ ] 휴지통에서 완전히 삭제
