### ISSUE TITLE
선생님은 최초 로그인 시에 기본 정보를 설정할 수 있다.

### ISSUE THREAD

**Issue by chayeoi** [chayeoi/learning-manager#2]
## Tasks

- [ ] Firestore에서 로그인한 유저 ID에 대한 유저 정보를 읽어오고, 없다면 기본 정보 설정 화면으로 리다이렉트.
- [ ] 기본 정보 설정 화면에서 정보 입력 후 저장 클릭 시 기본 정보를 파이어베이스에 저장.
- [ ] 기본 정보 저장 완료 후 대시보드로 리다이렉트.
