### ISSUE TITLE
선생님은 기관을 개설할 수 있다.

### ISSUE THREAD

**Issue by chayeoi** [chayeoi/learning-manager#3]
## Tasks

- [ ] 소속된 기관이 없을 경우, 기관 생성 화면으로 리다이렉트.
- [ ] 기관 생성 화면에서 기관 이름 중복 유무 validation.
- [ ] 기관 이름, 기관 주소, 이메일, 연락처(GitHub, Sentry 참고. 기관 이름이 URL이 될 것임을 헬퍼텍스트로 알림)
- [ ] 그룹 목록
- [ ] 기관이 존재할 경우 가장 최근에 접속헀던 기관 화면으로 리다이렉트.
