### ISSUE TITLE
선생님은 문제와 학생이 제출한 이미지를 확대해서 볼 수 있다. 

### ISSUE THREAD

**Issue by chayeoi** [chayeoi/learning-manager#4]
## Tasks

- [ ] 문제 이미지 클릭 시 전체 화면 이미지로 확대
- [ ] 응답 이미지 클릭 시 전체 화면 이미지로 확대
- [ ] 확대된 이미지 클릭 시 전체 화면 종료
